### ISSUE TITLE
Receiving sub events with rawPayload does not work

### ISSUE THREAD

**Issue by thielepaul** [dapr/go-sdk#256]
**Describe the bug**
receiving raw sub events as described [here](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/) does not work in go.

**To Reproduce**
Run the following app and send raw messages to the message broker

`main.go`:
```go
package main

import (
	"context"
	"log"
	"net/http"

	"github.com/dapr/go-sdk/service/common"
	daprd "github.com/dapr/go-sdk/service/http"
)

var sub = &common.Subscription{
	PubsubName: "mqtt-pubsub",
	Topic:      "test",
	Route:      "/test",
	Metadata:   map[string]string{"rawPayload": "true"},
}

func main() {
	s := daprd.NewService(":6002")
	if err := s.AddTopicEventHandler(sub, eventHandler); err != nil {
		log.Fatalf("error adding topic subscription: %v", err)
	}
	if err := s.Start(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("error listenning: %v", err)
	}
}

func eventHandler(ctx context.Context, e *common.TopicEvent) (retry bool, err error) {
	log.Printf("Subscriber received: %s", e.Data)
	return false, nil
}
```

`components/pubsub.yaml`:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt-pubsub
  namespace: default
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: "tcp://localhost:1883"
  - name: qos
    value: 1
  - name: retain
    value: "false"
  - name: cleanSession
    value: "true"
  - name: backOffMaxRetries
    value: "0"

```

**Expected behavior**
the raw message should be printed to stdout, but instead the following error is logged:
```
ERRO[0004] error deserializing cloud event in pubsub mqtt-pubsub and topic test: ReadMapCB: expect { or n, but found t, error found in #1 byte of ...|test|..., bigger context ...|test|...  app_id=checkout instance=KNX-CL-00117 scope=dapr.runtime type=log ver=1.6.0
ERRO[0004] Failed processing MQTT message: test/0: ReadMapCB: expect { or n, but found t, error found in #1 byte of ...|test|..., bigger context ...|test|...  app_id=checkout instance=KNX-CL-00117 scope=dapr.contrib type=log ver=1.6.0
```

It looks like the rawPayload=true is ignored. It works fine though with python and with the declarative approach, so I assumed the problem is in the go sdk.
