### ISSUE TITLE
Update the holopin.yaml to use the sdk badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/go-sdk#546]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqfdv4x24910fl5n4iwu5oa) for this repo:

```yaml
organization: dapr
defaultSticker: clrqfdv4x24910fl5n4iwu5oa
stickers:
  -
    id: clrqfdv4x24910fl5n4iwu5oa
    alias: sdk-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.
